### ISSUE TITLE
Mod fails to load

### ISSUE THREAD

**Issue by jplcz** [Gladon4/planet-arrakis#1]
Factorio: 2.0.23
Arrakis Mod: 0.1.0

Game fails to launch with the following error:
```
Error while running setup for space-location prototype "arrakis" (planet): medium-sand-rock (decorative) does not have an autoplace specification.
```
It appears to have some conflict with Alien Biomes (currently 0.7.2) mod.

**Comment by Gladon4** [comment]
I took out the decorative rocks in 0.2.0. So this no longer happens (for now)
