### ISSUE TITLE
Somes tips github

### ISSUE THREAD

**Issue by Fr-Dae** [Gladon4/planet-arrakis#4]
to make your life easier, here are a few recommendations from the github devs.

- make an issue for each need or problem.
- create a branch from this issue (as on the right)
- make your commit 
- PR with description
- when you merge the PR, close the issue.
- This will give you access to automatic release updates.
- if you use software such as gitkraken (which makes life much easier) you can create branches in one click.
- be careful, you'll need to manually assign a branch and an issue, as gitkraken doesn't do this (only locally).
- in the github options, I recommend checking ‘autoremove merged branch’.

- also my team has set up a workflow to automate certain functions, details can be found here

https://github.com/UnionRolistes/Documentation/blob/main/Template-Git/Auto-issue_EN-GB.md

**Comment by Gladon4** [comment]
While you are generally right, I dislike the way of using an issue per feature and then a branch from this issue for small solo projects. For multiple people and larger projects this is great and I use it there, but for solo projects (which this is for now), it just stops me from developing the way I like. Though your interest and help is appreciated.

**Comment by Fr-Dae** [comment]
The project will grow very quickly, so having a clean structure applied from the outset is the key to success and will avoid headaches later on, making your releases cleaner and giving credibility to your work.

Also, in the event of a reverse or specific bug, it will be easier to navigate between versions and PRs, and thus limit the time needed to find a bug.
